sudo: required
dist: bionic
language: node_js

node_js:
  - stable
services:
  - docker
before_install:
  - sudo rm /usr/local/bin/docker-compose # remove pre-installed docker-compose (too old)
  - bash .ci/setup-tools.sh
install:
  - "./version.sh"
  - make lint
  - "./tests/test.exp"
  - "./version.sh"
  - commander test tests/commander.yaml
  - make lint # rerun lint to see if output is different with .env in place
  - echo "docker_repo=$docker_repo" >> .env
  - echo "DOCKERREADME=yes" >> .env # add DOCKERREADME env var so that make publish also updates readme files on docker hub
  - echo "KCCONF_SERVER_SURVEYCLIENT_INTERVAL=0" >> kopano_server.env
  - echo "KOPANO_SURVEYCLIENT_ENABLED=false" >> kopano_konnect.env
  - echo "KOPANO_SURVEYCLIENT_ENABLED=false" >> kopano_kwmserver.env
  - travis_retry make build-all
script:
  - make test-ci
  - docker-compose down -v
  - make test-startup-meet-demo
deploy:
  - provider: script
    script:
      - echo "docker_repo=$docker_repo" >> .env
      - make publish
    on:
      branch: master
#cache: # uncomment to not load/upload trivy files each time
#  directories:
#    - $HOME/.cache/trivy
